/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

/* Initial Values for the types */
INSERT INTO [OPERATION.ACTION_TYPE] ([ACTION_TYPE_ID],[ACTION_TYPE_NAME]) VALUES(0,'ADD');
INSERT INTO [OPERATION.ACTION_TYPE] ([ACTION_TYPE_ID],[ACTION_TYPE_NAME]) VALUES(1,'EDIT');
INSERT INTO [OPERATION.ACTION_TYPE] ([ACTION_TYPE_ID],[ACTION_TYPE_NAME]) VALUES(2,'DELETE');
INSERT INTO [OPERATION.ACTION_TYPE] ([ACTION_TYPE_ID],[ACTION_TYPE_NAME]) VALUES(3,'REGISTER');
INSERT INTO [OPERATION.ACTION_TYPE] ([ACTION_TYPE_ID],[ACTION_TYPE_NAME]) VALUES(4,'LOGIN');
INSERT INTO [OPERATION.ACTION_TYPE] ([ACTION_TYPE_ID],[ACTION_TYPE_NAME]) VALUES(5,'LOGOUT');

GO

INSERT INTO [OPERATION.RESULT_TYPE] ([RESULT_TYPE_ID],[RESULT_TYPE_NAME]) VALUES(0,'SUCCESS');
INSERT INTO [OPERATION.RESULT_TYPE] ([RESULT_TYPE_ID],[RESULT_TYPE_NAME]) VALUES(1,'FAILURE');

GO

/* Testing Data */

/* Users */
INSERT INTO [SECURITY.AUTH.USERS]([USER_FIRST_NAME],[USER_LAST_NAME],[USER_MOBILE],[USER_EMAIL],[USER_PASSSWORD])
VALUES('Admin','Admin','00963947064930','mkhalifeh.ca@gmail.com','123');
INSERT INTO [SECURITY.AUTH.USERS]([USER_FIRST_NAME],[USER_LAST_NAME],[USER_MOBILE],[USER_EMAIL],[USER_PASSSWORD])
VALUES('Sigma','Test','00963','sigma.test@whatever.xyz','123');
GO

/* Products */
INSERT INTO [OPERATION.PRODUCT] ([PRODUCT_NAME]) VALUES ('LZJEX');
INSERT INTO [OPERATION.PRODUCT] ([PRODUCT_NAME]) VALUES ('HHWND');
INSERT INTO [OPERATION.PRODUCT] ([PRODUCT_NAME]) VALUES ('TLKLJ');
INSERT INTO [OPERATION.PRODUCT] ([PRODUCT_NAME]) VALUES ('EDCGY');
INSERT INTO [OPERATION.PRODUCT] ([PRODUCT_NAME]) VALUES ('DYMAG');
INSERT INTO [OPERATION.PRODUCT] ([PRODUCT_NAME]) VALUES ('AFNIJ');
INSERT INTO [OPERATION.PRODUCT] ([PRODUCT_NAME]) VALUES ('PXOZX');
INSERT INTO [OPERATION.PRODUCT] ([PRODUCT_NAME]) VALUES ('OQVLP');
INSERT INTO [OPERATION.PRODUCT] ([PRODUCT_NAME]) VALUES ('RNYWN');
INSERT INTO [OPERATION.PRODUCT] ([PRODUCT_NAME]) VALUES ('EMYIT');
INSERT INTO [OPERATION.PRODUCT] ([PRODUCT_NAME]) VALUES ('NOKCA');
INSERT INTO [OPERATION.PRODUCT] ([PRODUCT_NAME]) VALUES ('AQUHY');
INSERT INTO [OPERATION.PRODUCT] ([PRODUCT_NAME]) VALUES ('ADYHR');
INSERT INTO [OPERATION.PRODUCT] ([PRODUCT_NAME]) VALUES ('WQOWB');
INSERT INTO [OPERATION.PRODUCT] ([PRODUCT_NAME]) VALUES ('IPOYD');

GO

/* Categories */
INSERT INTO [OPERATION.CATEGORY] ([CATEGORY_NAME]) VALUES ('RHQ');
INSERT INTO [OPERATION.CATEGORY] ([CATEGORY_NAME]) VALUES ('KFP');
INSERT INTO [OPERATION.CATEGORY] ([CATEGORY_NAME]) VALUES ('ULT');
INSERT INTO [OPERATION.CATEGORY] ([CATEGORY_NAME]) VALUES ('YPB');
INSERT INTO [OPERATION.CATEGORY] ([CATEGORY_NAME]) VALUES ('RBV');

GO

/* Relations Demo M:M */
INSERT INTO [OPERATION.CATEGORY_PRODUCT] ([CATEGORY_ID] ,[PRODUCT_ID]) VALUES (3,11);
INSERT INTO [OPERATION.CATEGORY_PRODUCT] ([CATEGORY_ID] ,[PRODUCT_ID]) VALUES (3,13);
INSERT INTO [OPERATION.CATEGORY_PRODUCT] ([CATEGORY_ID] ,[PRODUCT_ID]) VALUES (2,14);
INSERT INTO [OPERATION.CATEGORY_PRODUCT] ([CATEGORY_ID] ,[PRODUCT_ID]) VALUES (2,5);
INSERT INTO [OPERATION.CATEGORY_PRODUCT] ([CATEGORY_ID] ,[PRODUCT_ID]) VALUES (2,12);
INSERT INTO [OPERATION.CATEGORY_PRODUCT] ([CATEGORY_ID] ,[PRODUCT_ID]) VALUES (4,3);
INSERT INTO [OPERATION.CATEGORY_PRODUCT] ([CATEGORY_ID] ,[PRODUCT_ID]) VALUES (3,3);
INSERT INTO [OPERATION.CATEGORY_PRODUCT] ([CATEGORY_ID] ,[PRODUCT_ID]) VALUES (4,10);
INSERT INTO [OPERATION.CATEGORY_PRODUCT] ([CATEGORY_ID] ,[PRODUCT_ID]) VALUES (3,10);
INSERT INTO [OPERATION.CATEGORY_PRODUCT] ([CATEGORY_ID] ,[PRODUCT_ID]) VALUES (5,11);
INSERT INTO [OPERATION.CATEGORY_PRODUCT] ([CATEGORY_ID] ,[PRODUCT_ID]) VALUES (4,9);
INSERT INTO [OPERATION.CATEGORY_PRODUCT] ([CATEGORY_ID] ,[PRODUCT_ID]) VALUES (3,15);
INSERT INTO [OPERATION.CATEGORY_PRODUCT] ([CATEGORY_ID] ,[PRODUCT_ID]) VALUES (3,15);
INSERT INTO [OPERATION.CATEGORY_PRODUCT] ([CATEGORY_ID] ,[PRODUCT_ID]) VALUES (3,8);
INSERT INTO [OPERATION.CATEGORY_PRODUCT] ([CATEGORY_ID] ,[PRODUCT_ID]) VALUES (2,10);
INSERT INTO [OPERATION.CATEGORY_PRODUCT] ([CATEGORY_ID] ,[PRODUCT_ID]) VALUES (5,10);
INSERT INTO [OPERATION.CATEGORY_PRODUCT] ([CATEGORY_ID] ,[PRODUCT_ID]) VALUES (5,2);
INSERT INTO [OPERATION.CATEGORY_PRODUCT] ([CATEGORY_ID] ,[PRODUCT_ID]) VALUES (2,12);
INSERT INTO [OPERATION.CATEGORY_PRODUCT] ([CATEGORY_ID] ,[PRODUCT_ID]) VALUES (3,7);

GO